"""Initial migration 2

Revision ID: 51ae18926d4b
Revises: c7d7f34f02f1
Create Date: 2025-02-07 00:37:23.340732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ae18926d4b'
down_revision = 'c7d7f34f02f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_scraped_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swiggy_product_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blinkit_product_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zepto_product_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swiggy_product_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blinkit_product_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zepto_product_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('zepto_product_count')
        batch_op.drop_column('blinkit_product_count')
        batch_op.drop_column('swiggy_product_count')

    with op.batch_alter_table('live_scraped_products', schema=None) as batch_op:
        batch_op.drop_column('zepto_product_count')
        batch_op.drop_column('blinkit_product_count')
        batch_op.drop_column('swiggy_product_count')

    # ### end Alembic commands ###
